pipeline {
  agent any
  stages {
    stage('build and scan'){
      steps{
        withSonarQubeEnv('sonarqube'){
          sh 'chmod +x demo/gradlew'
          sh 'demo/gradlew clean build sonarqube'
        }
      }
    }
  }
}
